blended_version = 3.9

# Configuration is automatically generated by Blended, feel free to edit any values below
website_name = "LilyPond"
website_description = "Music Notation for Everyone"
website_description_long = "" # Use for things like author bio on a blog
website_license = "GPL 3.0"
author_name = "The LilyPond Team"
website_language = "en"
home_page_list = "yes"

plugins = [] # Place all needed plugins in here

# The following values are used for FTP uploads
ftp_server = "localhost"
ftp_username = "user"
ftp_password = "pass"
ftp_port = 21
ftp_upload_path = "public_html/myWebsite"
