blended_version = 4.8

# Configuration is automatically generated by Blended (http://jmroper.com/blended), feel free to edit any values below
website_name = "LilyPond"
website_description = "Music Notation for Everyone"
website_description_long = "" # Use for things like author bio on a blog
website_license = "2017 the LilyPond Team"
author_name = "John Roper"
website_language = "en"
home_page_list = "yes"

plugins = [["google_fonts"]] # Place all needed plugins in here
minify_css = False
minify_js = False

# The following values are used for FTP uploads
ftp_server = "localhost"
ftp_username = "user"
ftp_password = "pass"
ftp_port = 21
ftp_upload_path = "public_html/myWebsite"

google_fonts = [["Merriweather"],["Open Sans", "300,600"]]
